Feature/9 compose refactoring
Apptive2022-1/EasyWine pull request #10
Opened 2022-10-03 09:29 UTC by Kick-snare

resolved #9 

# 변경점 👍
- @wona825 @nnoonjy 의 ui 코드 리팩토링
- 코드를 모듈화하고 가독성 좋게, 더 컴팩트하게 변경
 
# 리팩토링 🛠
- 변수명, 함수명 이것저것 수정
- 불필요한 composable 제거
- 보일러 플레이트 코드 최대한 제거
- 하드코딩 지양
 
# 비고 ✏
- 꼭 확인 부탁드립니다.
- git을 이용한 협업 프로젝트입니다! git 꼬이면 약간 답없이 생산성만 저하하게 되니 무작성 push 하지않기! PR을 이용합시다. 👍

2022-10-03 15:10 UTC, nnoonjy requested changes
코드가 확 간결해졌네요 수고하셨습니다 ~! 코멘트 달아놓은 것들 한 번 확인해주세요 :)

2022-10-03 15:10 UTC, nnoonjy commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyButtons.kt
> +					id = if (isLeft) R.drawable.page_previous else R.drawable.page_previous
else문 뒤에서는 page_next 이미지를 불러와야하지 않나요 ?

2022-10-03 15:10 UTC, nnoonjy commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyButtons.kt
> +				text = if (isLeft) "이전으로 돌아가기" else "다음으로 넘어가기",
"다음으로 넘어가기" 버튼은 텍스트 다음에 이미지가 와야하는데 반대로 될 것 같습니다.

2022-10-03 15:20 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyButtons.kt
> +					id = if (isLeft) R.drawable.page_previous else R.drawable.page_previous
그렇네요

2022-10-03 15:21 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyButtons.kt
> +				text = if (isLeft) "이전으로 돌아가기" else "다음으로 넘어가기",
그렇네요 수정해서 반영했습니다. 두 개 다 확인해보고 이상없으면 resolve conversation 누르면 됨

2022-10-04 08:24 UTC, wona825 approved these changes
해주신 피드백들 다 좋아서 그대로 반영하면 될 것 같습니다 !!

2022-10-04 08:58 UTC, nnoonjy reviewed
👌👍

2022-10-04 09:00 UTC, nnoonjy approved these changes
🧑

2022-10-04 09:00 UTC, merged