Feature/jiwon
Apptive2022-1/EasyWine pull request #14
Opened 2022-10-06 17:11 UTC by wona825

# 변경점 👍
 -  SurveyScreen 구현 
 - components code 추가 및 수정 (for SurveyScreen)
 

# 비고 ✏
 - 상황 카테고리에서 사용되는 복수선택 버튼은 구현되지 않은 상태
 - 정도에 따라 다섯개 중 하나의 버튼을 고르는 '바디감' 카테고리 화면을 기준으로 구현
 
# 리뷰 부탁드립니다 :)

2022-10-07 05:07 UTC, nnoonjy requested changes

2022-10-07 05:07 UTC, nnoonjy commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +            //.fillMaxSize()
상단에 뒤로가기 버튼이랑 메뉴버튼 추가해야할 것 같아요

2022-10-07 05:34 UTC, nnoonjy requested changes
💛

2022-10-07 05:34 UTC, nnoonjy commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +        SurveyTitle("오늘의 와인을 위한 ","바디감 ","질문이에요.")
SurveyTitle부분도 설문조사 부분과 함께 스크롤이 되어야해서 SurveyMainContent에 포함시켜주어야할 것 같습니다

2022-10-07 05:34 UTC, nnoonjy commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyQuestion.kt
> +					tint = if (selectedValue.value == label) check_button else uncheck_button,
선택시에 체크동그라미로 바뀌어야하는데 분홍색 사각형이 뜹니당

2022-10-07 05:34 UTC, nnoonjy commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +            Spacer(modifier = Modifier.size(30.dp))
이 두 버튼 간격을 좀 더 넓어야할 것 같은데 이건 제가 설정해둔 값이니까 나중에 제가 수정하겠습니다
혹시 제가 까먹으면 알려주세요 ...

2022-11-04 05:29 UTC, nnoonjy approved these changes

2022-11-04 14:20 UTC, Kick-snare requested changes
고생하셨습니다! 피드백한 부분 고쳐주시고 사용하지 않는 import 문 제거 해주시면 될거 같습니다 👍

2022-11-04 14:20 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +        Spacer(modifier = Modifier.height(30.dp))
Topbar 가 스크롤에 따라오고 있습니다.
<img width="473" alt="image" src="https://user-images.githubusercontent.com/46425142/199993567-b1e726dc-fe2e-4ff3-ab7f-62d6e047b017.png">
디자이너님의 의도와 다른거 같은데 수정이 필요해보입니다. SurveyMainContent 안으로 들어가야 할 거 같습니다
<img width="309" alt="image" src="https://user-images.githubusercontent.com/46425142/199994130-14285d86-c110-48f9-a3a6-401866996a56.png">

2022-11-04 14:20 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
>  import androidx.compose.ui.tooling.preview.Preview
사용되지 않는 의존성들은 제거해주시면 더 좋을거같아요!

2022-11-04 14:20 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +                SurveyTitle("오늘의 와인을 위한 ","바디감 ","질문이에요.")
SurveyTitle 에 들어가는 텍스트들은 SurveyMainContent에서 인자로 받아오는 것이 추후 값을 받아오는데 더 편할 것 같습니다

2022-11-04 14:20 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveySituationScreen.kt
> +    Column(
스펠링 수정 부탁드립니다!

2022-11-04 14:20 UTC, Kick-snare commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyMultipleCheck.kt
> +            .clip(RoundedCornerShape(30))
높이를 주고 clip을 하니 버튼이 짤리고 있습니다
<img width="453" alt="image" src="https://user-images.githubusercontent.com/46425142/199997169-35d594ff-dbc7-44b6-9e5a-8dd1014b5046.png">
modifier을 건들이는 대신 Button compsable에 shape = RoundedCornerShape(12.dp)를 주는 방법이 더 좋을 거 같습니다
12.dp 인 이유는
<img width="360" alt="image" src="https://user-images.githubusercontent.com/46425142/199997389-1b394784-0f70-4bee-9819-4048c6862291.png">

2022-11-04 14:49 UTC, wona825 commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +        Spacer(modifier = Modifier.height(30.dp))
넵 SurveyMainContent 안에 위치하도록 수정했습니다 !

2022-11-04 14:50 UTC, wona825 commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
>  import androidx.compose.ui.tooling.preview.Preview
전체적으로 전부 제거 완료했습니다 !

2022-11-04 14:50 UTC, zvvony commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveyScreen.kt
> +                SurveyTitle("오늘의 와인을 위한 ","바디감 ","질문이에요.")
넵 수정했습니다 !

2022-11-04 14:50 UTC, wona825 commented on app/src/main/java/com/apptive/easywine/presentation/Survey/SurveySituationScreen.kt
> +    Column(
수정 완료했습니다 !

2022-11-04 14:50 UTC, wona825 commented on app/src/main/java/com/apptive/easywine/presentation/components/SurveyMultipleCheck.kt
> +            .clip(RoundedCornerShape(30))
clip 대신 shape로 변경했습니다 !

2022-11-04 14:51 UTC, Kick-snare approved these changes
nice work! 👍

2022-11-04 14:52 UTC, merged